final List<String> categoryList = [
  "Art and Collectibles",
  "Automotive",
  "Baby Products",
  "Beauty and Personal Care",
  "Books",
  "Clothing",
  "Crafts and Hobbies",
  "Electronics",
  "Fitness and Exercise",
  "Furniture",
  "Grocery and Gourmet",
  "Health and Wellness",
  "Home and Kitchen",
  "Jewelry",
  "Outdoor and Garden",
  "Pet Supplies",
  "Tools and Home Improvement",
];